name: forca_vendas
description: Projeto de força de vendas feito em Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  sqflite: ^2.0.0+4
  crypto: ^3.0.1
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  shared_preferences: ^2.0.8
  cherry_toast: ^1.0.2
  intl: ^0.17.0
  flutter_custom_clippers: ^2.0.0
  geolocator: ^7.7.1
  auto_size_text: ^3.0.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
